import {describe,it,expect,beforeEach,afterEach} from 'vitest';
import fs from 'node:fs';import path from 'node:path';
import {makeCompany,type Store,type Project,type Task} from '../src/domain/company';
import {createProject,advanceProjects,runManager,projectWorks,stopProject,beforeProjectCall,autonomousStatus,handleTaskError,resumeProjectWork} from './projects';
import {saveFile} from './workspace';
const models=[{id:'gpt-5.6-sol',name:'Sol',efforts:['low','high'],defaultEffort:'low'},{id:'gpt-5.6-luna',name:'Luna',efforts:['low','medium'],defaultEffort:'low'}];
let s:Store,p:Project,root:string,out:string;
beforeEach(()=>{fs.mkdirSync('docs/verification/project-tests',{recursive:true});root=fs.mkdtempSync(path.resolve('docs/verification/project-tests/case-'));out=path.join(root,'outputs');s={version:1,boss:'測試老闆',companies:[makeCompany('公司','studio',models)],tasks:[],paused:false,maxTasksPerDay:30};p=createProject(s,s.companies[0],models,'goal','做一個加法工具');});
afterEach(()=>{fs.rmSync(root,{recursive:true,force:true})});
function planned(){return {decision:'proceed',title:'加法工具',reason:'依目標交付',assumptions:[],category:'none',question:'',steps:[{title:'實作加法',employeeId:s.companies[0].employees[1].id,model:models[0].id,effort:'low',acceptance:['可正確加法']}]}}
async function run(t:Task,r:unknown){t.state='working';await runManager(t,s,models,root,out,()=>{},async()=>r)}
async function planning(){await run(s.tasks[0],planned());return projectWorks(s,p)[0]}
function draft(t:Task,pass=true){t.attempt++;t.state='approve';t.result='內部草稿';const rel=`workspaces/${t.id}/draft/v${t.attempt}/main.js`;t.pendingFiles=[{path:rel,sha256:saveFile(root,rel,'module.exports=(a,b)=>a+b')}];t.checks=[{name:'實際行為',passed:pass,output:pass?'3':'失敗'}]}
function review(t:Task,verdict='pass'){return {verdict,reason:'審查說明',evidence:(t.acceptance||[]).map(criterion=>({criterion,passed:verdict==='pass',evidence:'main.js 及行為測試'})),guidance:verdict==='pass'?'':'修正加法',category:'none',question:'',targetTaskId:t.id,delivery:{summary:'加法工具已完成',howToUse:['載入 main.js 後呼叫函數'],limitations:['僅 JavaScript 數值'],entryTaskId:t.id,entryPath:'main.js'}}}
async function approve(t:Task){advanceProjects(s);await run(s.tasks.at(-1)!,review(t))}
describe('主管規畫與交付門檻',()=>{
 it('主管回覆後相同缺口再出現，不再浪費第二次協調呼叫',async()=>{const t=await planning();t.state='blocked';t.error='缺最新外部資料';advanceProjects(s);await run(s.tasks.at(-1)!,{decision:'direct',reason:'先處理本機部分',direction:'使用已有資料',assumptions:[],category:'none',question:''});t.state='blocked';t.error='缺最新外部資料';const count=s.tasks.length;advanceProjects(s);expect(p.status).toBe('blocked');expect(p.message).toContain('同一個必要缺口');expect(s.tasks).toHaveLength(count)});
 it('審查中的檔案版本改變，舊 PASS 作廢',async()=>{const t=await planning();draft(t);advanceProjects(s);const manager=s.tasks.at(-1)!;manager.state='working';let resolve!:(v:unknown)=>void;const pending=runManager(manager,s,models,root,out,()=>{},()=>new Promise(r=>{resolve=r}));t.executionRevision=1;t.state='queued';resolve(review(t));await pending;expect(manager.state).toBe('cancelled');expect(t.reviewedAttempt).toBeUndefined();expect(t.state).toBe('queued')});
 it('HTML 即使主管 PASS，沒有操作驗收時不能正式發布',async()=>{const t=await planning();draft(t);const rel=`workspaces/${t.id}/draft/v${t.attempt}/index.html`;t.pendingFiles=[{path:rel,sha256:saveFile(root,rel,'<button onclick="throw Error(1)">壞掉的按鈕</button>')}];await approve(t);advanceProjects(s);const final=s.tasks.at(-1)!;await run(final,{...review(t),delivery:{...review(t).delivery,entryPath:'index.html'},evidence:[`整案目標：${p.goal}`,`${t.id}：所有階段驗收標準已通過且成果相容`].map(criterion=>({criterion,passed:true,evidence:'文字審查'}))});expect(p.status).toBe('blocked');expect(p.blockReason).toBe('validation');expect(p.candidateDelivery?.entryPath).toBe('index.html');expect(t.files).toEqual([]);expect(fs.existsSync(out)).toBe(false)});
 it('最終存檔失敗後回復可見狀態，不能留下半套完成品',async()=>{const t=await planning();draft(t);await approve(t);advanceProjects(s);const final=s.tasks.at(-1)!;final.state='working';let saves=0;await expect(runManager(final,s,models,root,out,()=>{if(++saves===2)throw new Error('injected save failure')},async()=>({...review(t),evidence:[`整案目標：${p.goal}`,`${t.id}：所有階段驗收標準已通過且成果相容`].map(criterion=>({criterion,passed:true,evidence:'實際檔案'}))}))).rejects.toThrow('injected');expect(p.status).not.toBe('completed');expect(t.files).toEqual([]);expect(p.delivery).toBeUndefined()});
 it('排程轉為暫停時立即保存，不依賴後續有可執行工作',async()=>{const t=await planning();t.state='blocked';t.consultations=2;const file=path.join(root,'state.json');let writes=0;advanceProjects(s,()=>{writes++;fs.writeFileSync(file,JSON.stringify(s))});expect(JSON.parse(fs.readFileSync(file,'utf8')).projects[0].status).toBe('blocked');expect(writes).toBe(1);advanceProjects(s,()=>{writes++});expect(writes).toBe(1)});
 it('按目標建立帶模型及驗收標準的工作，不受舊件數目標阻擋',async()=>{s.companies[0].goals.push({id:'old',name:'10件',target:10,baseline:0});const t=await planning();expect(t.title).toBe('實作加法');expect(t.acceptance).toEqual(['可正確加法']);expect(t.files).toEqual([])});
 it('拒絕主管指定不存在模型',async()=>{const r=planned();r.steps[0].model='fake';await expect(run(s.tasks[0],r)).rejects.toThrow('不可用');expect(projectWorks(s,p)).toHaveLength(0)});
 it('預算不足不接受過多計畫',async()=>{p.maxCalls=3;await expect(planning()).rejects.toThrow('超出');});
 it('兩次審查通過前不發布；最終 PASS 才公開檔案',async()=>{const t=await planning();draft(t);expect(fs.existsSync(out)).toBe(false);await approve(t);expect(t.state).toBe('done');expect(t.files).toHaveLength(0);advanceProjects(s);const final=s.tasks.at(-1)!;const requirements=[`整案目標：${p.goal}`,`${t.id}：所有階段驗收標準已通過且成果相容`];await run(final,{...review(t),evidence:requirements.map(criterion=>({criterion,passed:true,evidence:'已核對程式'}))});expect(p.status).toBe('completed');expect(t.files.length).toBeGreaterThan(0);expect(fs.existsSync(path.join(out,t.files[0]))).toBe(true)});
 it('FAIL 退回修正，未開放任何結果',async()=>{const t=await planning();draft(t);advanceProjects(s);await run(s.tasks.at(-1)!,review(t,'fail'));expect(t.state).toBe('queued');expect(t.feedback).toContain('修正');expect(t.files).toHaveLength(0);expect(fs.existsSync(out)).toBe(false)});
 it('測試失敗不得被模型 PASS 繞過',async()=>{const t=await planning();draft(t,false);await approve(t);expect(t.reviews?.at(-1)?.verdict).toBe('fail');expect(t.reviewedAttempt).toBeUndefined()});
 it('缺少驗收標準證據的 PASS 被攔下',async()=>{const t=await planning();draft(t);advanceProjects(s);await run(s.tasks.at(-1)!,{...review(t),evidence:[{criterion:'摘要看起來好',passed:true,evidence:'自述'}]});expect(t.state).toBe('queued')});
 it('草稿被修改後不得用舊 hash 審查',async()=>{const t=await planning();draft(t);fs.writeFileSync(path.join(root,t.pendingFiles![0].path),'被改動');advanceProjects(s);await expect(run(s.tasks.at(-1)!,review(t))).rejects.toThrow('校驗不符')});
 it('一般問題請示主管後回到員工，不向老闆升級',async()=>{const t=await planning();t.state='blocked';t.error='選哪種數值格式';advanceProjects(s);await run(s.tasks.at(-1)!,{decision:'direct',reason:'這是主管可決定的設計',direction:'使用 JavaScript number，標示精度限制',assumptions:['一般數值'],category:'none',question:''});expect(t.state).toBe('queued');expect(t.feedback).toContain('number');expect(p.escalation).toBeUndefined()});
 it('付費重大決策只提請老闆，不自行恢復',async()=>{const t=await planning();t.state='blocked';advanceProjects(s);await run(s.tasks.at(-1)!,{decision:'escalate',reason:'涉及購買資料',direction:'',assumptions:[],category:'cost',question:'是否另行處理資料採購？'});expect(p.status).toBe('blocked');expect(p.escalation?.category).toBe('cost');expect(t.state).toBe('blocked')});
 it('請示上限後安靜暫停',async()=>{const t=await planning();t.state='blocked';t.consultations=2;advanceProjects(s);expect(p.status).toBe('blocked');expect(p.escalation).toBeUndefined()});
 it('呼叫上限阻止下一次推論',()=>{p.calls=p.maxCalls;expect(()=>beforeProjectCall(p,s)).toThrow('上限');expect(p.calls).toBe(p.maxCalls)});
 it('主管執行途中停止後，不採納遲到結果',async()=>{let resolve!:(v:unknown)=>void;const task=s.tasks[0];task.state='working';const pending=runManager(task,s,models,root,out,()=>{},()=>new Promise(r=>{resolve=r}));stopProject(s,p);resolve(planned());await pending;expect(p.status).toBe('stopped');expect(projectWorks(s,p)).toHaveLength(0)});
 it('有主管專案時不重複開案',()=>{expect(()=>createProject(s,s.companies[0],models,'goal','第二案')).toThrow('現有主管專案')});
 it('文件來源會固定在專案與後續任務，不只停留在畫面',()=>{stopProject(s,p);const document={id:'11111111-1111-4111-8111-111111111111',name:'需求.docx',format:'docx' as const,originalRef:'document-imports/1/original.docx',originalSha256:'a'.repeat(64),parsedRef:'document-imports/1/parsed.md',parsedSha256:'b'.repeat(64),characters:20,parser:'Docling' as const,parserVersion:'2.127.0',localOnly:true as const,limitations:[]};const next=createProject(s,s.companies[0],models,'goal','依文件製作','文件內容',18,undefined,document);expect(next.inputDocument).toEqual(document);expect(s.tasks.at(-1)?.inputDocument).toEqual(document)});
 it('舊授權不可擴張成新版自主規畫',()=>{s.companies[0].autoDispatch={enabled:true,dailyLimit:1,intervalMinutes:30,authorizedAt:new Date().toISOString()};expect(autonomousStatus(s.companies[0],s)).toContain('尚未授權')});
 it('自主模式完成本日上限後不再開案',()=>{p.mode='autonomous';p.status='completed';s.companies[0].autoDispatch={enabled:true,version:2,dailyLimit:1,intervalMinutes:30,authorizedAt:new Date().toISOString()};expect(autonomousStatus(s.companies[0],s)).toContain('每日')});
 it('模型滿載不浪費呼叫請示主管，也不排下一案',async()=>{const t=await planning();handleTaskError(s,t,new Error('Selected model is at capacity.'));const count=s.tasks.length;advanceProjects(s);expect(p.status).toBe('blocked');expect(s.tasks).toHaveLength(count);expect(p.escalation).toBeUndefined()});
  it('模型失效後，手動繼續會套用員工目前選定的模型與強度',async()=>{const t=await planning();handleTaskError(s,t,new Error('此任務模型已不可用，主管已暫停'));const employee=s.companies[0].employees.find(e=>e.id===t.employeeId)!;employee.model='gpt-5.6-luna';employee.effort='medium';resumeProjectWork(s,p,t,'改用可用模型');expect(t.model).toBe('gpt-5.6-luna');expect(t.effort).toBe('medium');expect(t.state).toBe('queued');expect(t.logs.at(-1)?.text).toContain('已套用目前員工模型')});
  it('一般缺口仍交由主管處理',async()=>{const t=await planning();handleTaskError(s,t,new Error('缺少欄位規格'));advanceProjects(s);expect(s.tasks.at(-1)?.kind).toBe('consult');expect(p.status).toBe('running')});
 it('修正上限暫停後，手動繼續會重做受影響下游',async()=>{const r=planned();r.steps.push({...r.steps[0],title:'下游文件'});await run(s.tasks[0],r);const [a,b]=projectWorks(s,p);draft(a);draft(b);await approve(a);b.state='done';b.reviewedAttempt=b.attempt;a.state='approve';a.revisions=2;advanceProjects(s);await run(s.tasks.at(-1)!,review(a,'fail'));expect(p.status).toBe('blocked');expect(a.state).toBe('blocked');resumeProjectWork(s,p,a,'修正後重驗');expect(a.state).toBe('queued');expect(b.state).toBe('queued');expect(b.reviewedAttempt).toBeUndefined();expect(b.pendingFiles).toBeUndefined()});
 it('每日預算不足時手動派工不留下半成品專案',()=>{stopProject(s,p);const count=s.projects!.length;s.maxTasksPerDay=2;expect(()=>createProject(s,s.companies[0],models,'manual','手動','',18,[{title:'工作',employeeId:s.companies[0].employees[1].id,model:models[0].id,effort:'low',reason:'手動'}])).toThrow('預算不足');expect(s.projects).toHaveLength(count)});
 it('主管計畫可以讓獨立工作並行，整合工作等待兩邊完成',async()=>{const r=planned();r.steps=[{...r.steps[0],dependsOn:[]},{...r.steps[0],title:'獨立文件',employeeId:s.companies[0].employees[2].id,dependsOn:[]},{...r.steps[0],title:'整合',dependsOn:[0,1]}] as any;await run(s.tasks[0],r);const [a,b,c]=projectWorks(s,p);expect(a.dependsOn).toEqual([]);expect(b.dependsOn).toEqual([]);expect(c.dependsOn).toEqual([a.id,b.id])});
 it('主管計畫不接受循環或未存在的前置工作',async()=>{const r=planned();(r.steps[0] as any).dependsOn=[1];await expect(run(s.tasks[0],r)).rejects.toThrow('工作相依');expect(projectWorks(s,p)).toHaveLength(0)});
 it('主管交付格式錯誤會在預算內自行修正，不立刻丟給老闆',()=>{const t=s.tasks[0];t.attempt=1;p.calls=1;handleTaskError(s,t,new Error('主管尚未提供白話成果說明與使用步驟'));expect(t.state).toBe('queued');expect(t.feedback).toContain('使用步驟');expect(p.escalation).toBeUndefined();t.attempt=3;handleTaskError(s,t,new Error('格式錯誤'));expect(p.status).toBe('blocked')});
});
