import {BrowserEvidence} from './BrowserEvidence';
import {useState} from 'react';import type {Company,Project,Store} from '../domain/company';import {api} from '../services/agentGateway';import {Modal} from './Modal';import {DocumentView} from './DocumentView';import {TradingResearchResult} from './TradingChart';
export function Deliveries({company,store,onOpenTask,refresh}:{company:Company;store:Store;onOpenTask:(id:string)=>void;refresh:()=>Promise<void>}){
 const [opened,setOpened]=useState<{project:Project;content:string;html:boolean;taskId:string;index:number;candidate?:boolean}>(),[error,setError]=useState('');
 const projects=(store.projects||[]).filter(p=>p.companyId===company.id).slice().reverse();
 const chartTask=opened&&!opened.candidate?store.tasks.find(t=>t.projectId===opened.project.id&&t.files.some(file=>file.endsWith('/tradingagents-evidence.json'))):undefined;
 async function open(p:Project){setError('');try{const d=await api(`/projects/${p.id}/delivery`);setOpened({...d,project:p})}catch(e){setError((e as Error).message)}}
 async function stop(p:Project){try{await api(`/projects/${p.id}/stop`,'POST',{});await refresh()}catch(e){setError((e as Error).message)}}
 return <section className="deliveries"><h2>你的任務與成果</h2>{!projects.length&&<div className="delivery-empty"><strong>交代一件事，完成後在這裡取用</strong><p>主管會安排人手、處理一般問題、檢查成品。你不需要逐項分派或閱讀內部報告。</p></div>}{projects.map(p=>{const tasks=store.tasks.filter(t=>t.projectId===p.id),works=tasks.filter(t=>t.kind==='work');return <article className={'delivery-card '+p.status} key={p.id}><span className="project-state">{p.status==='completed'?'已做好，可以使用':p.status==='stopped'?'已停止':p.escalation?'需要你決定一件事':p.blockReason==='validation'?'待操作驗收':p.status==='blocked'?'已暫停，尚未完成':'正在替你製作'}</span><h3>{p.title}</h3>{p.status==='completed'&&p.delivery?<><p>{p.delivery.summary}</p><button className="btn primary" onClick={()=>void open(p)}>開啟成果</button><h4>怎麼使用</h4><ol>{p.delivery.howToUse.map((x,i)=><li key={i}>{x}</li>)}</ol>{p.delivery.limitations.length>0&&<details><summary>限制與未完成事項</summary><ul>{p.delivery.limitations.map((x,i)=><li key={i}>{x}</li>)}</ul></details>}</>:<p>{p.message}</p>}{p.status==='blocked'&&p.blockReason==='validation'&&p.candidateDelivery&&<button className="btn" onClick={()=>void open(p)}>檢視待驗收作品</button>}{!['completed','stopped'].includes(p.status)&&<><p className="exp">階段審查 {works.filter(t=>t.reviewedAttempt===t.attempt&&t.attempt>0).length}／{works.length} 項通過 · {tasks.filter(t=>t.state==='working').length} 人正在處理</p><button className="btn small task-stop" onClick={()=>void stop(p)}>停止這個任務</button></>}<BrowserEvidence project={p}/><details><summary>{p.status==='completed'?'其他檔案與驗收紀錄':'查看目前進度'}</summary>{tasks.map(t=><button className="project-task" key={t.id} onClick={()=>onOpenTask(t.id)}>{t.title}<small>{t.stage}{t.files.length?` · ${t.files.length} 個檔案`:''}</small></button>)}</details></article>})}{error&&<div className="error">{error}</div>}{opened&&<Modal title={opened.project.title} onClose={()=>setOpened(undefined)}>{opened.candidate&&<p className="note">這是待操作驗收的作品，尚未列為完成品；主管的文字 Review 不代表功能已實測。</p>}{opened.html?<iframe title={opened.candidate?"待操作驗收的作品":"已完成的作品"} className="artifact-frame" sandbox="allow-scripts" src={`/api/projects/${opened.project.id}/preview`}/>:<DocumentView text={opened.content}/>} {chartTask&&<TradingResearchResult task={chartTask}/>} {!opened.candidate&&<a className="btn" href={`/api/download/${opened.taskId}/${opened.index}`}>下載主要成果</a>}</Modal>}</section>
}
