import {useState} from 'react';
import type {Company,Project,Store} from '../domain/company';
import {api} from '../services/agentGateway';
import {Modal} from './Modal';
const statusName:Record<Project['status'],string>={planning:'主管規畫中',running:'員工執行與主管審查',reviewing:'整案驗收中',blocked:'主管已暫停',completed:'PASS／OK · 已交付',stopped:'已停止／休息'};
export function ManagerOrderDialog({company,refresh,onClose,initialMode='goal',initialGoal='',input='',documentId}:{company:Company;refresh:()=>Promise<void>;onClose:()=>void;initialMode?:'goal'|'autonomous';initialGoal?:string;input?:string;documentId?:string}){
 const [mode,setMode]=useState(initialMode),[goal,setGoal]=useState(initialGoal),[maxCalls,setMaxCalls]=useState(18),[limit,setLimit]=useState(1),[interval,setInterval]=useState(30),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const manager=company.employees[0];
 async function submit(){setBusy(true);setError('');try{await api(`/companies/${company.id}/manager-projects`,'POST',{mode,goal,input,documentId,maxCalls,dailyLimit:limit,intervalMinutes:interval,resumeOffice:true});await refresh();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Modal title="下令主管規畫與審查" onClose={onClose}><div className="manager-flow">主管規畫 → 員工實作 → 主管 Review → 整案驗收</div><label className="field">安排方式<select aria-label="主管安排方式" value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="goal">我給目標，由主管指揮完成</option><option value="autonomous">主管依公司類型自主規畫專案</option></select></label><label className="field">{mode==='goal'?'要完成的目標':'給主管的方向與限制（可留白）'}<textarea aria-label="主管專案目標" value={goal} onChange={e=>setGoal(e.target.value)} maxLength={12000} placeholder={mode==='goal'?'例如：設計值得開發的 APP，交付產品方案與可操作的原型，明示未查證假設。':'例如：以小型企業的營運工具為主，每案交付可用的程式與說明。'}/></label><p className="exp">{manager.title} {manager.name} 使用 {manager.model}／{manager.effort} 規畫與審查。員工的模型和強度由主管依任務選擇。一般問題先請示主管，重大決策才交給你。</p><label className="field">每案模型呼叫上限（含規畫、實作、請示、Review）<input aria-label="每案模型呼叫上限" type="number" min={4} max={60} value={maxCalls} onChange={e=>setMaxCalls(Number(e.target.value))}/></label>{mode==='autonomous'&&<div className="model-fields"><label className="field">每日最多專案數<input aria-label="每日自主專案上限" type="number" min={1} max={5} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><label className="field">完成後隔幾分鐘開下一案<input type="number" min={5} max={1440} value={interval} onChange={e=>setInterval(Number(e.target.value))}/></label></div>}<p className="note">送出後開始使用 Codex 額度；每項最多退回修正 2 次、請示 2 次，達上限會休息。未通過整案審查的檔案只留內部草稿。關閉或重新整理辦公室頁面會停止全部工作。</p><p className="exp">目前可做文件、程式文字與隔離 JavaScript 測試；無法取得即時市場資料。主管必須標明假設與能力缺口。</p>{error&&<p className="error">{error}</p>}<button className="btn primary" disabled={busy||(mode==='goal'&&!goal.trim())} onClick={()=>void submit()}>{mode==='goal'?'下令主管完成目標':'啟動自主規畫與審查'}</button></Modal>
}
function ProjectCard({project,store,refresh,onOpenTask}:{project:Project;store:Store;refresh:()=>Promise<void>;onOpenTask?:(id:string)=>void}){
 const [answer,setAnswer]=useState(''),[limit,setLimit]=useState(project.maxCalls),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const tasks=store.tasks.filter(t=>t.projectId===project.id),works=tasks.filter(t=>t.kind==='work');
 async function act(action:string){setBusy(true);setError('');try{await api(`/projects/${project.id}/${action}`,'POST',action==='resume'?{answer,maxCalls:limit}:{});await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <article className={'manager-project '+project.status}><div className="project-state">{project.blockReason==='validation'?'待操作驗收':project.escalation?'需要老闆重大決策':statusName[project.status]}</div><h4>{project.title}</h4><p>{project.message}</p><div className="exp">模型呼叫 {project.calls}／{project.maxCalls} · 階段通過 {works.filter(t=>t.reviewedAttempt===t.attempt&&t.attempt>0).length}／{works.length}</div>{project.assumptions.length>0&&<details><summary>主管採用的假設</summary><ul>{project.assumptions.map((a,i)=><li key={i}>{a}</li>)}</ul></details>}<details><summary>查看指揮與 Review 紀錄（{tasks.length}）</summary>{tasks.map(t=><button className="project-task" key={t.id} onClick={()=>onOpenTask?.(t.id)}>{t.title}<small>{t.stage}</small></button>)}</details>{project.escalation&&<div className="error">{project.escalation.question}</div>}{project.status==='blocked'&&(project.blockReason!=='validation'||project.browserContract)&&<details><summary>{project.escalation?'回覆重大決策':'檢視後手動要求主管繼續'}</summary><label className="field">補充方向<textarea aria-label="回覆主管" value={answer} onChange={e=>setAnswer(e.target.value)} maxLength={6000}/></label><label className="field">此案呼叫總上限<input type="number" min={4} max={60} value={limit} onChange={e=>setLimit(Number(e.target.value))}/></label><button className="btn" disabled={busy||store.paused} onClick={()=>void act('resume')}>下令主管繼續</button></details>}{!['completed','stopped'].includes(project.status)&&<button className="btn task-stop" onClick={()=>void act('stop')}>停止此專案／休息</button>}{error&&<div className="error">{error}</div>}</article>
}
export function ManagerPanel({company,store,refresh,onOpenTask}:{company:Company;store:Store;refresh:()=>Promise<void>;onOpenTask?:(id:string)=>void}){
 const [mode,setMode]=useState<'goal'|'autonomous'>('goal'),[open,setOpen]=useState(false),[error,setError]=useState('');
 const projects=(store.projects||[]).filter(p=>p.companyId===company.id).slice().reverse(),active=projects.some(p=>!['completed','stopped'].includes(p.status));
 return <section className="auto-panel"><h3>主管指揮中心</h3><p className="exp">你給目標，或讓主管自主提案。每案皆經 Review，PASS 才交付。</p><div className="manager-mode-actions"><button className="btn" disabled={active} onClick={()=>{setMode('goal');setOpen(true)}}>給目標，請主管安排…</button><button className="btn" disabled={active} onClick={()=>{setMode('autonomous');setOpen(true)}}>下令主管自主規畫…</button></div>{company.autoDispatch?.enabled&&<><p className="exp">自主規畫已授權 · 每日最多 {company.autoDispatch.dailyLimit} 案</p><button className="btn small" onClick={async()=>{try{await api(`/companies/${company.id}/auto-dispatch`,'POST',{action:'disable'});await refresh()}catch(e){setError((e as Error).message)}}}>關閉後續自主開案</button></>}<p className="exp">{company.dispatchStatus||'預設手動；下令後才開始'}</p>{company.autoDispatch?.lastError&&<p className="error">{company.autoDispatch.lastError}</p>}{error&&<p className="error">{error}</p>}{projects.slice(0,6).map(p=><ProjectCard key={p.id} project={p} store={store} refresh={refresh} onOpenTask={onOpenTask}/>)}{open&&<ManagerOrderDialog company={company} refresh={refresh} onClose={()=>setOpen(false)} initialMode={mode} initialGoal={mode==='autonomous'?company.autoDispatch?.instruction||'':''}/>}</section>
}
