import fs from 'node:fs';
import assert from 'node:assert/strict';
const base='http://127.0.0.1:4317';
const before=JSON.parse(fs.readFileSync('docs/verification/production-before-page-close.json','utf8'));
const health=await (await fetch(base+'/api/health')).json();
const state=await (await fetch(base+'/api/state')).json();
assert.equal(health.version,'2.1.0');
assert.equal(state.paused,true);
assert.equal(state.maxConcurrentTasks,2);
assert.equal(state.pageConnected,false);
assert.deepEqual(state.tasks,before.tasks);
const pausedOnRestart=before.projects.filter((p:any)=>!['completed','stopped','blocked'].includes(p.status)).map((p:any)=>p.id);
assert.deepEqual(state.projects,before.projects.map((p:any)=>pausedOnRestart.includes(p.id)?{...p,status:'blocked',message:'服務中斷，主管已暫停；請檢視紀錄後手動繼續。'}:p));
assert.equal(state.boss,before.boss);
const clean=(companies:any[])=>companies.map(({dispatchStatus,...company})=>({...company,autoDispatch:company.autoDispatch?{...company.autoDispatch,enabled:false}:undefined}));
assert.deepEqual(clean(state.companies),clean(before.companies));
const html=await (await fetch(base)).text();
assert(html.includes('/assets/index-'));
const result={at:new Date().toISOString(),health,paused:state.paused,pageConnected:state.pageConnected,maxConcurrentTasks:state.maxConcurrentTasks,allOriginalTasksPreserved:state.tasks.length,allOriginalProjectsPreserved:state.projects.length,pausedOnRestart,companiesPreserved:state.companies.length,noModelInference:true};
fs.writeFileSync('docs/verification/production-page-close.json',JSON.stringify(result,null,2));
console.log(JSON.stringify(result,null,2));
